### ISSUE TITLE
Current path implementation brokes with same path length because flow binds given path

### ISSUE THREAD

**Issue by ilya-m32** [lttb/flown#5]
Error example (implementation was copied from [Path](https://github.com/lttb/flown/blob/master/src/Path/index.js) is [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgD6ACgIYYAWYAvGADwDyAXGAwEYBWeAxhgDRhiAPgAUDAcQCUNIWAAkAYVIwYdVGDAAyMCLoBBAQCEBCgQBEBAUVEBtA2GNhTYC2EsBdadVlzLMPAC2eAB2GAAquHhqGhq+-kGhEfh0cYEh4ZEpfmmJmakJGcniYHpCRmVOFWZC6mBWQpK12rr2js7VInZGJuaeMvLZBUlRtbGD6cNZ8RN547lFAqXlJjUa5g1NOvrdlZ2tJn3eA9PzIzHHOYVR+TMLJRWGq3WVjRrN2w62rYc+c1fRMRup0Yiye5VeWi2pT2PwuQ0yo1YtVBjQkNWw+EE5AojBY7C4vDRNHkShUdBI2IExWE6AxBDgnGJAG8KHgsCwAIwAJgAzAIKHAKCwAOQIRDCgC+AG50CJuTyWGRKHQGRwBDZhaysML3BtUFKRKLxYrsSrOOrNYKdRsgA).

Works fine with previous implementation (which was commented due to multiple declare, I guess?)

**Comment by ilya-m32** [comment]
cast @lttb

**Comment by ilya-m32** [comment]
actually, second impl does not work for longer paths either
Here is an [example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMABQENCALAHgHkAuMZgIwCsMBjQgBpqAPjABeMABIAwjRgxGAClRgwAMjBLGAQXZSA0hlIBnFiOEAhYTOEARYQFFhANXYBtHVZv2nAXRFVNS0XAEoJMSlHGAwAWwwAO0IAFXIMRloGFmFPbzBbMDsApxFQoM1tPWkjU3M8gocwNzBcsGt8+wCgtSUwiOlouMSUtIy6JmYcrzabYsLS8q1dfRqzZgsZjqaPafaZLuCQ8PFIwfik1IoxrMmW3bmZBbUK5erjNY325tbLA+De46nGLnEZXTITKZzSxPDRLKqGd51bZ3P49PonAbA4aXdK3HQLULCKiBVAAE34MBo+EoUAArgkBABLOAJMA4caMIK3KjCXY+QpOVAiJS3H78xqOPyhfRnbGjcHZO71TobRwk8l8SnUsB0hmEZms9lZLlE3nKwpCkVTc1FaWYoYXeUc0V8-JzOzqilUmn0pkstkck3UM2bGSWl31KUyrGOsHO61tB6BDVan16g0B41qbkhyzhhO-O1RGOg9IKl1Q5Ne7W6v2GwPZ01gHT5lFF2Wx3G8qua706336-1GiHBsDJYXcu3JdDYPBEfvpofjJThADeAF9uodtzvd9vUGQKGA4Dxkgg4BIwKuAOQ0a-sG+ce9gACMb-Xm9QwGA+TgsRBJD0IyJhgDAjIJJQqAANxKG+L7sAqJ7cGecA5Le17CNeT4BGU37HvggHAaB4EYNBSjXvQcD0M+CqrvQxgPpR9DsBRVHXh+aH0aQGFgKx1E4UAA)

So far I have come to stupid but working (with all my additional tests) [solution](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgD6ACgIYYAWYAvKmPWAGRgAUAPAPIA0YxPAgjwBCPAMI8AIjwCiAPhYBtQWBFhxYKWGkBdHhwCUNWXQamAJNJh4AtngB2GACq48bC1dsPn+N5Zv2nF18PAO9Xd38vIO4wfllheLVEiUS5fRN6ZnYYvljhMUkZeSV8tUKtbUNqWVYDIwzTMAjPQJ9m0KD2qLa-FrDgyNbXGLiEsWTU2XSGrM4eXOVVdRTFRYKNXTA66qbejp6Q7vC9o4G+6IFEoUTRCfTTWZyBUuXitbKNqpqWbZquobO+2OhwB-36IyuNzu6AerDmvGeKnGqxem1+uxB-TBnROAIhYyS9wYj3miKWb1RX1qVOxB0GWNx4MuBNu01h2VJeRUFJUaJpjJxmIusUhRMycKeXOuKN5VJ+-KFdPOPnx3LZxIlnLiqz5Rgx9OFcTFTE1CJFOrl6Npw0u+gA3Og8AAPHBwABOGDA2HwvHIFE4AC4tgAjABWeAAxhh5jVqE1RKQYDA2CQ-ZyOLIHY1sznc6ZMC4wHAw44EHAaGAAN4AclI1aDNeD9bAAEY2wBfdvoYDANRwawtL0UACWAGcwDBh3YCKg7Sw2y2g2RKGxi6HS3AeApa9WeNWm9opqge0W3UOxxOp3hZyxqxQ4BRm8v-ZWKHgsA37xQg3eH9XO1ud7vruYC-o+h76EAA) (`_Path` is curried and has reversed arguments, but it can be changed easily)

**Comment by lttb** [comment]
Thank you for the issue and fix!

Fixed in https://github.com/lttb/flown/pull/6
Released in v0.2.1
